### PR TITLE
Form/Editable label failing with glScissor

### LINKED ISSUE #55: Error while running the code from text input tutorial
I've got an error while trying to run the code from the tutorial:
```
#!/usr/bin/env python3

import glooey
import pyglet

pyglet.font.add_file('form/Lato-Regular.ttf')
pyglet.font.load('Lato Regular')

class WesnothForm(glooey.Form):
    custom_alignment = 'center'

    class Label(glooey.EditableLabel):
        custom_font_name = 'Lato Regular'
        custom_font_size = 10
        custom_color = '#b9ad86'
        custom_alignment = 'top left'
        custom_horz_padding = 5
        custom_top_padding = 5
        custom_width_hint = 200

    class Base(glooey.Background):
        custom_center = pyglet.resource.texture('form_center.png')
        custom_left = pyglet.resource.image('form_left.png')
        custom_right = pyglet.resource.image('form_right.png')

window = pyglet.window.Window()
gui = glooey.Gui(window)

form = WesnothForm()
form.push_handlers(on_unfocus=lambda w: print(f"Form input: '{w.text}'"))
gui.add(form)

pyglet.app.run()
```
```
Traceback (most recent call last):
  File "c:\Users\cklke\Desktop\test_pyglet\form\form_test.py", line 33, in <module>
    pyglet.app.run()
  File "C:\Users\cklke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "C:\Users\cklke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyglet\app\base.py", line 169, in run
    timeout = self.idle()
  File "C:\Users\cklke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyglet\app\base.py", line 245, in idle
    window.dispatch_event('on_draw')
  File "C:\Users\cklke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\cklke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyglet\event.py", line 408, in dispatch_event     
    if handler(*args):
  File "C:\Users\cklke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\glooey\root.py", line 120, in on_draw
    self.batch.draw()
  File "C:\Users\cklke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyglet\graphics\__init__.py", line 564, in draw   
    func()
  File "C:\Users\cklke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyglet\text\layout.py", line 603, in set_state    
    glScissor(self._clip_x, self._clip_y - self._clip_height, self._clip_width, self._clip_height)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```
How to fix this error? I'm using Python 3.9.7, pyglet 1.5.21 and glooey 0.3.6.

### PR DESCRIPTION
**Pull request by Rahuum**
Fixes #55

### CODE REVIEW

**Comment by kalekundert** [comment]
Thanks for figuring this out.  I think you need to keep the `aligned_rect.round()` call, though, because it actually rounds to the *nearest* integer, while `int()` just truncates the fractional component of the number.  In other words:
```
>>> int(1.9)
1
>>> round(1.9)
2
```
---
Alternatively, it might be better to fix the `vecrec.Rect.round()` method to just return ints in the first place.  This relates to an obscure behavior of the `round()` function that I didn't know about until just now:
```
>>> help(round)
Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.
```
So the reason `Rect.round()` is returning floats is that we're explicitly passing 0 as the number of digits.  If we rewrite `Rect.round()` as show below, it will behave exactly like `round()` and return ints when no digits are specified:
```
def round(self, *args, **kwargs):
        """ Round the dimensions of the given rectangle to the given number of digits. """
        self._left = round(self._left, *args, **kwargs)
        self._bottom = round(self._bottom, *args, **kwargs)
        self._width = round(self._width, *args, **kwargs)
        self._height = round(self._height, *args, **kwargs)
```
I think that would be a more robust solution.

**Comment by kalekundert** [comment]
In fact, I'll just make that change to `Rect.round()`.  It'll just take me a few minutes...

**Comment by kalekundert** [comment]
Ok, I made the aforementioned changes to `Rect.round()`.  I think that also fixes #55 without the need for these changes.  Let me know if that isn't the case.

**Comment by Rahuum** [comment]
So that did fix it, though it does have the long-term issue of making it less self-documenting.

It may be worth it to investigate something like
```python
def round(self, digits=None):
        """ Round the dimensions of the given rectangle to the given number of digits. """
        self._left = round(self._left, digits)
        self._bottom = round(self._bottom, digits)
        self._width = round(self._width, digits)
        self._height = round(self._height, digits)
```

or something.
But I'll close this out since my own issue is actually closed, that's more a doco suggestion than anything.

**Comment by kalekundert** [comment]
Yeah, that occurred to me right after I finished making the change.  I might go back and fix it when I get some time.

**Pull request closed without merging**
